### ISSUE TITLE
package was unpublished from pypi?

### ISSUE THREAD

**Issue by thestick613** [meherett/python-hdwallet#1]
Hello, any idea what happened here?

https://pypi.org/project/python-hdwallet/

Someone else might register this namespace and publish something else.

**Comment by DjMoren** [comment]
I don't know if it used to have another name, but al least now, it is https://pypi.org/project/hdwallet/

**Comment by thestick613** [comment]
It's still here on the google cache:
https://webcache.googleusercontent.com/search?q=cache:t4P7sjOYWtMJ:https://pypi.org/project/python-hdwallet/0.1.1/+&cd=2&hl=en&ct=clnk&gl=ro&client=safari

I believe it's the same project.

**Comment by meherett** [comment]
@DjMoren, Thanks!

@thestick613 Yes, It's the same project. I only changed the namespace from `python-hdwallet` to `hdwallet`.

**Comment by DjMoren** [comment]
Here is the change: https://github.com/meherett/python-hdwallet/commit/9aed0e9683a92eb54ad8ae24265cb4dd64ffee4e#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
