### ISSUE TITLE
Cannot create HDWallet from a `zpub` extended public key

### ISSUE THREAD

**Issue by yawhide** [meherett/python-hdwallet#11]
Howdy again,

I am having trouble created an HDWallet instance using this zpub address. 
I am pretty confident this is a real zpub because I can go to blockchair and see the history of transactions https://blockchair.com/bitcoin/xpub/zpub6oN4tLvpVbb3setcn6eStWCFSqpxMBYn7XkCgyERhg8ccW8tU8RCe4NTzNpH6nPgxiy1du5sDdzPdt6Q2vQmPsYy2gmV1M4NY3CscMgqsJZ
I'll show you a list of things I tried:

```python
>>> from hdwallet import HDWallet, BIP84HDWallet

>>> zpub = 'zpub6oN4tLvpVbb3setcn6eStWCFSqpxMBYn7XkCgyERhg8ccW8tU8RCe4NTzNpH6nPgxiy1du5sDdzPdt6Q2vQmPsYy2gmV1M4NY3CscMgqsJZ'

>>> hdwallet = HDWallet(symbol='BTC')
>>> hdwallet.from_xpublic_key(xpublic_key=zpub)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/env/lib/python3.6/site-packages/hdwallet/hdwallet.py", line 296, in from_xpublic_key
    _deserialize_xpublic_key[5], curve=SECP256k1
  File "~/env/lib/python3.6/site-packages/ecdsa/keys.py", line 46, in from_string
    curve.verifying_key_length, len(string)))
ecdsa.keys.MalformedPointError: Malformed encoding of public point. Expected string 64 bytes long, received 33 bytes long string
```

I then tried to use `BIP84HDWallet`
```python
>>> hdwallet84 = BIP84HDWallet(symbol='BTC')
>>> hdwallet84.from_xpublic_key(xpublic_key=zpub)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/env/lib/python3.6/site-packages/hdwallet/hdwallet.py", line 296, in from_xpublic_key
    _deserialize_xpublic_key[5], curve=SECP256k1
  File "~/env/lib/python3.6/site-packages/ecdsa/keys.py", line 46, in from_string
    curve.verifying_key_length, len(string)))
ecdsa.keys.MalformedPointError: Malformed encoding of public point. Expected string 64 bytes long, received 33 bytes long string
```

I am using hdwallet v1.2.0

Any ideas why this isnt working?

**Comment by yawhide** [comment]
weird. i deleted my virtual env and re-installed my requirements and it works. sorry about that!

also while I have you here, how do you run the test cases? I couldnt find any information in your README

i created a venv by running `python3.6 -m venv env`, then `pip install pip==20.1`, then `pip install -r requirements.txt`. Finally i run `pytest tests/test_from_xpublic_key.py` and i get the following error

```
$ pytest tests/test_from_xpublic_key.py
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=hdwallet/
  inifile: ~/code/meherett/python-hdwallet/pytest.ini
  rootdir: ~/code/meherett/python-hdwallet
  ```

**Comment by meherett** [comment]
Yes Sir, I have plans. For the error, you didn't install `pytest-cov` package. So, install it first then it works, sir :)

To install
```
pip install -e .[tests] -r requirements.txt
```
or
```
pip install pytest-cov
```
For more https://github.com/meherett/python-hdwallet/blob/master/setup.py#L33

**Comment by meherett** [comment]
Or if you don't want use test coverage, you can also remove this `--cov=hdwallet/` flag from pytest.ini file.

**Comment by yawhide** [comment]
i am such a python noob. thanks :)
