### ISSUE TITLE
BTC wallet does not generate native segwit addresses when a native segwit derivation path is passed, e.g. "m/84'/0'/0'/0/0"

### ISSUE THREAD

**Issue by loupiote** [meherett/python-hdwallet#3]
BTC wallet does not generate native segwit addresses when a native segwit derivation path is passed, e.g. "m/84'/0'/0'/0/0"

Native segwit BTC addresses start by 'bc1q', instead of '1' for legacy addresses (i.e. path m/44'/0'/...)

Same issue with "nested segwit' (i.e. path m/49'/0'/...), that should generate addresses starting with '3'.

**Comment by meherett** [comment]
@loupiote For now, It's only working for legacy addresses especially for BIP44 paths, and it will be supported in the next version. :)

**Comment by loupiote** [comment]
Thanks!

**Comment by meherett** [comment]
@loupiote  All are now implemented on v1.0.0 package.

**Comment by loupiote** [comment]
great, thanks! :)
