### ISSUE TITLE
Move click, click-aliases, and tabulate to extras_require

### ISSUE THREAD

**Issue by Tayum** [meherett/python-hdwallet#46]
As of version `hdwallet==2.1.0`, `click`, `click-aliases`, and `tabulate` are considered must-have dependencies for `hdwallet` package.
But actually, they're necessary only in case `hdwallet`'s CLI is used, but it's not always a case.

This creates some problems in case other dependencies or the project itself which uses `hdwallet` have different version range for these dependencies, e.g. `click<8.0.0`.

It's proposed to move the aforementioned dependencies from `install_requires` to `extras_require` in `setup.py` to be able to include them only if CLI part of package is considered to be used.
`cli` is the proposed key for these list of packages in `extras_require` dictionary.

**Comment by meherett** [comment]
Noted.

**Comment by Tayum** [comment]
Hey @meherett, what do you think about it?

**Comment by Tayum** [comment]
@meherett, hey there. Thanks!

Any ways to gently push this for `2.1.1` -- and ETAs for that to happen? :)

**Comment by meherett** [comment]
@Tayum, Just create a new pull request for this issue on this repo then I will push it into PyPI `2.1.1` package.

**Comment by meherett** [comment]
Done [v2.1.1](https://github.com/meherett/python-hdwallet/releases/tag/v2.1.1)!
