### ISSUE TITLE
Additional language support for mnemonics

### ISSUE THREAD

**Issue by DoDzilla-ai** [meherett/python-hdwallet#47]
I have no experience thus I am asking directly: Is it possible to add different languages (like Turkish or German) for mnemonic words?  If so, how?

**Comment by meherett** [comment]
@DoDzilla-ai,
 
Yes, It's possible to use different languages but the language it needs confirmation. On this library, the languages are dependent on [python-mnemonic](https://github.com/trezor/python-mnemonic) library. You can also add languages by creating pull request on python-mnemonic [wordlists](https://github.com/trezor/python-mnemonic/tree/master/src/mnemonic/wordlist) repo.
