### ISSUE TITLE
implementing transactions

### ISSUE THREAD

**Issue by TheHackitect** [meherett/python-hdwallet#49]
Hi, 
Thanks once again for this useful tool. I have been able to integrate hdwallet with my app.

I am stucked at signing, verifying and broadcasting of transactions. Please I need help.

**Comment by meherett** [comment]
Sure @TheHackitect, Just send me PM on Telegram @meherett username.

**Comment by TheHackitect** [comment]
Thanks so much. I Just sent a DM .
