### ISSUE TITLE
Generate New Wallet

### ISSUE THREAD

**Issue by victorpoffo** [meherett/python-hdwallet#65]
Hey, this code creates a new wallet or just generate a random mnemonic?

MNEMONIC= generate_mnemonic(language="english", strength=128)
PASSPHRASE: Optional[str] = None  # "meherett"
bip44_hdwallet: BIP44HDWallet = BIP44HDWallet(cryptocurrency=EthereumMainnet)
bip44_hdwallet.from_mnemonic(
        mnemonic=MNEMONIC, language="english", passphrase=PASSPHRASE

How can i initialize a wallet with my mnemonic words? 

Thanks!

**Comment by meherett** [comment]
Hi @victorpoffo,
 
```python3
# To initialize your wallet, use this
MNEMONIC: str = "..."
# instead of generating new mnemonic words
MNEMONIC: str = generate_mnemonic(language="english", strength=128)
```
