### ISSUE TITLE
Incorrect deriving in any custom HDWallet [bug]

### ISSUE THREAD

**Issue by tagunegusvatitepe** [meherett/python-hdwallet#66]
Hello. I noticed that any custom deriving with CUSTOMHDWallet.from_path function raise gluing old __init__ path and new submitted path. So the result is absolutely different keys. I tried to find problem by myself but code is too difficult to me.
![2022-09-27 05_16_17-C__python_polygon_test json - Notepad++  Administrator](https://user-images.githubusercontent.com/114456089/192416568-a7658125-1013-438e-a739-928df31b5a93.png)

I'm absolutely sure that it is a bug, cuz if I forbid your (module) deriving and place my own required path, everything working fine and I get correct keys.  
![2022-09-27 05_17_25-C__Users_hope_AppData_Local_Programs_Python_Python38_Lib_site-packages_hdwallet_](https://user-images.githubusercontent.com/114456089/192418917-7d502d06-c239-40f7-ab37-97e5b993dc98.png)

**Comment by forevox** [comment]
same problem
