### ISSUE TITLE
Add public_key_uncompressed method

### ISSUE THREAD

**Issue by jh1995** [meherett/python-hdwallet#8]
Please add a method "public_key_uncompressed" so that we can get the long version of the public key, if needed.

If someone falls here searching how to get the long key before the feature request is implemented, you need to locate hdwallet.py file in your python3 library path and clone the public_key method by changing the return statement to return self.uncompressed() .

**Comment by meherett** [comment]
It's Done on v1.2.0 :) Now, To get uncompressed public key, just change compressed parameter to set `False` when you are calling `public_key` function.

Fore more https://github.com/meherett/python-hdwallet/blob/master/hdwallet/hdwallet.py#L732
