### ISSUE TITLE
create an address from an existing xpub string

### ISSUE THREAD

**Issue by yawhide** [meherett/python-hdwallet#9]
Hello,

I was looking through the api in this package and I couldn't find a way to generate a bip32, bip44, etc bitcoin address given an xpub string.

I looked through this file: https://github.com/meherett/python-hdwallet/blob/master/hdwallet/hdwallet.py and it seems there are ways to generate address if you have the seed, mnemonic phrase, private key, etc but not with just an xpub string.

Am I missing something?

Thanks

**Comment by meherett** [comment]
Duplicated #4 

Hey @yawhide, Now you can get master from xpublic key on v1.2.0 package.

For more you can see this example of xpub https://github.com/meherett/python-hdwallet/blob/master/examples/from_xpublic_key.py

Thanks :)

**Comment by yawhide** [comment]
thank you! i totally missed the example folder 🤦
